### PR TITLE
New domains

### PR DESCRIPTION
**Pull request by zoaics**
Domains added:
- dlscold-niitro.com
- rustrouletle.com
- discorb-nitro.ru
- dlscrod-nltro.shop
- dlscrod-nltro.ru
- inlnk.ru/dnYPDK
- steam-airdrop.com

### CODE REVIEW

**Review by nikolaischunk — APPROVED** [review]
You can merge it yourself :)

**Comment by zoaics** [comment]
Gotcha, though I can't seem to find the option to merge the pr

**Comment by nikolaischunk** [comment]
that's odd, I thought once I approve the changes you can. I will do it then, thanks for contributing :)

**Comment by zoaics** [comment]
> that's odd, I thought once I approve the changes you can. I will do it then, thanks for contributing :)

No worries!

**Pull request merged**
