### PR TITLE
Updated amount

### PR DESCRIPTION
**Pull request by BradGamez**

### CODE REVIEW

**Comment by NanduWasTaken** [comment]
Wait that amount is not correct

**Comment by BradGamez** [comment]
> Wait that amount is not correct

I mean if you look at the domain-list.json there is 8,732 domains listed.

**Comment by NanduWasTaken** [comment]
> > Wait that amount is not correct
> 
> I mean if you look at the domain-list.json there is 8,732 domains listed.

I deleted it , how can you reply to that

**Comment by BradGamez** [comment]
> > > Wait that amount is not correct
> 
> > 
> 
> > I mean if you look at the domain-list.json there is 8,732 domains listed.
> 
> 
> 
> I deleted it , how can you reply to that

I honestly have no idea. Wizardry 😅

**Comment by NanduWasTaken** [comment]
> > > > Wait that amount is not correct
> > 
> > 
> > > 
> > 
> > 
> > > I mean if you look at the domain-list.json there is 8,732 domains listed.
> > 
> > 
> > I deleted it , how can you reply to that
> 
> I honestly have no idea. Wizardry 😅

Are you the one you frend request me in discord

**Comment by BradGamez** [comment]
> > > > > Wait that amount is not correct
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I mean if you look at the domain-list.json there is 8,732 domains listed.
> 
> > > 
> 
> > > 
> 
> > > I deleted it , how can you reply to that
> 
> > 
> 
> > I honestly have no idea. Wizardry 😅
> 
> 
> 
> Are you the one you frend request me in discord

Yup

**Comment by SkyDiscovery** [comment]
> > Wait that amount is not correct
> 
> I mean if you look at the domain-list.json there is 8,732 domains listed.

@BradGamez, I think an update of the domain count only makes sense after re-sorting into the right lists related to #151

**Comment by NanduWasTaken** [comment]
Huhhhhh

**Pull request closed without merging**
