### PR TITLE
Update domain-list.json

### PR DESCRIPTION
**Pull request by AzgarDev**
Will always contribute a little everytime.

### CODE REVIEW

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Please remove the things behind the / and check if the domains already exist before creating an PR.
So instead of `discojd.com/newyears` do `discojd.com`!

**Comment by AzgarDev** [comment]
Done.

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Remove `gif-discorde.com`

**Comment by AzgarDev** [comment]
Done, BTW, the had already removed the "/" from the gif-discorde, but github didn't update it for some reason. Sorry, wont happen again, this is my first time making pull requests and its really confusing for me atm.

**Comment by nikolaischunk** [comment]
> Okay done, btw, this is my first time using pull requests, sorry, this wont happen again lmao.

Don't worry, I appreciate it anyway. Glad that you understood anything so far. :)

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
please still remove `gif-discorde.com` since its already in the list

**Comment by AzgarDev** [comment]
Done, holy shit this is embarrasing. I swear i removed it but for some reason i didn't click on commit lmao

**Review by nikolaischunk — APPROVED** [review]
Good Job :)
From now on you know how to create good Pull Requests!

**Pull request merged**
