### PR TITLE
New Domain

### PR DESCRIPTION
**Pull request by TeemoCell**
Domain is used to steal facebook accounts

### CODE REVIEW

**Comment by Frexzs** [comment]
I need to know how to create a pishing site links

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Please add Domain into Suspicious List and add evidence in your PR.

**Comment by qtAmyVT** [comment]
This domain seems to be defunct, however it was used for a german facebook scam.

**Comment by TeemoCell** [comment]
Why in suspicious domains? It was used in a German Facebook scam. I can add even more link. They try to scam you like 100 times a day. My chat box is full of that spam.

**Comment by nikolaischunk** [comment]
Please provide evidence for the scam you have witnessed.
If you do so, feel free to re open the PR :)

**Comment by qtAmyVT** [comment]
Here is the evidence, however the domain seems to be defunct.

**Comment by TeemoCell** [comment]
> Here is the evidence, however the domain seems to be defunct. 

tyvm, didn't found the url in my history anymore.

**Pull request closed without merging**
