### PR TITLE
New Domain

### PR DESCRIPTION
**Pull request by guyguy303**
```
"glfts.net",
"https://cutt.us/getpremiumdiscord",
"cutt.us",
"glft-games.com/ref=36938629502",
"glft-games.com",
```

### CODE REVIEW

**Comment by nikolaischunk** [comment]
Please combine those PRs into a single one.

**Comment by guyguy303** [comment]
What does PRs mean?

**Comment by guyguy303** [comment]
You mean Pull request?

**Comment by guyguy303** [comment]
Done

**Comment by guyguy303** [comment]
Anyway is that the way that i can get a Contributors?

**Comment by nikolaischunk** [comment]
> Anyway is that the way that i can get a Contributors?

If you `contribute` Code to the repo, you will get listed as Contributor yesss

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Please add those links you listed to the PR and not only in the description of the PR.
Only add not yet added links please

**Comment by guyguy303** [comment]
What does it mean "not only in the description of the PR"

**Comment by nikolaischunk** [comment]
PR means Pullrequest.
At the moment, you added the Domains in the Description of the Pullrequest. This is mostly useless, please add these Domains into the `domain-list.json`

**Comment by guyguy303** [comment]
So i need to fork?

**Comment by guyguy303** [comment]
Done

**Comment by nikolaischunk** [comment]
image
as you can see, are there only two  domains added. it makes no sense to merge a commit like this.
If you don't understand what I mean, please learn how git & github first.

My request is pretty simple, not sure what there is not to understand about.

**Comment by guyguy303** [comment]
Ok i will be right back when i ready

**Pull request closed without merging**
