### PR TITLE
Added Domains

### PR DESCRIPTION
**Pull request by nikolaischunk**

### CODE REVIEW

**Comment by nikolaischunk** [comment]
```
"dlscordbasic.com",
"srteaamcomunlty.pp.ua",
"steamcammunity.site",
"streamcornrnunlty.org",
"steancommnulity.online",
"dicsordgifts.com",
"steammcomunnitty.ru",
"steancommnuilty.online",
"eventsfor-hypesq.gq",
"free-dirscord-nitro.com",
"betadiscord-news.uk",
"steamncommunty.store",
"navi52.com",
"steavmcommuacity.ru",
"navi26.com",
"navi41.com",
"navi81.com",
"lp3xc.site",
"navi31.com",
"navi54.com",
"faze9.com",
"navi66.com",
"stearncommunitly.ru",
"webs-minting.com",
"steanconunity.com",
"betadiscord-new.com",
"steamcomnmunty.online",
"steancomminutly.ru",
"steamcoomynlty.org.ru",
"steamcoomynlty.net.ru",
"steamcoomynlty.pp.ru",
"store-hypixel.gift",
"e-premiumtime.com",
"steamcommnutity.com",
"steamncommunity.com",
"steancomminuty.cfd",
"stearncomnmunlty.ru",
"steancommunuty.co",
"steancommunite.org",
"steeamcommunnity.com",
"hypixelverification.ru",
"steamcomnmuunty.com",
"steamcommumnty.store",
"steamecomunitty.ru",
"steamcommurnnity.com",
"steamconunity.com",
"steancommuniti.ru",
"staemcommunutty.com",
"steanncommunity.shop",
"steanncommunity.pro",
"steamcomnununity.com",
"sleamcommnunity.com",
"player78000419.asia",
"pc825000398.asia",
"steamcoomynity.pp.ru",
"steamcoomynity.net.ru",
"steamconmunuty.com",
"dlscord-nitro-month.com",
"steamsomnmunilty.ru",
"stearncommuity.ru",
"steanconmunlity.ru",
"steampowerred.co",
"steamcommcuntiy.com",
"steamcommuunitly.ru",
"steamcommunitysgo54013.asia",
"steam-communnity.online",
"steamncommunity.org",
"djscordbasic.com",
"steanmcommunity.co",
```

**Review by nsde — COMMENTED** [review]
Most of them don't work (404 or just no webpage at all)

**Comment by nsde** [comment]
Navi81 is the only one that worked for me

**Comment by nikolaischunk** [comment]
> Most of them don't work (404 or just no webpage at all)

This is because they work only on specific paths e.g. `navi167.com/path/discord/abc`. For simplicity we add the Domain not the specific Path related to the scam.

**Pull request merged**
