### PR TITLE
Added more domains

### PR DESCRIPTION
**Pull request by NanduWasTaken**
I added couldflare.com discordbot.com discordapi.cf

### CODE REVIEW

**Comment by NanduWasTaken** [comment]
I will get more links

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Hey, thankyou for contributin!
I need you to
1. Show me where you got all those domains?
2. Move the domains that are unrelated to Discord into [suspicious-domains.json](https://github.com/nikolaischunk/discord-phishing-links/blob/main/suspicious-list.json)

**Comment by NanduWasTaken** [comment]
> Hey, thankyou for contributin! I need you to
> 
> 1. Show me where you got all those domains?
> 2. Move the domains that are unrelated to Discord into [suspicious-domains.json](https://github.com/nikolaischunk/discord-phishing-links/blob/main/suspicious-list.json)

I got some of the domain from the a server which reports the scam links of discord and I got some from reported sites

And i will move it to suspicious-domains.json

**Comment by NanduWasTaken** [comment]
@nikolaischunk  done!

**Comment by lucapolesel** [comment]
Consider sorting the two arrays

**Comment by NanduWasTaken** [comment]
> Consider sorting the two arrays

Explain??????

**Comment by SkyDiscovery** [comment]
I added the domains of this PR to my PR and sorted them.

**Comment by NanduWasTaken** [comment]
> Consider sorting the two arrays

You mean in the alphabetic order 
Yeah i will consider that but the pull request is closed so 👌

**Comment by NanduWasTaken** [comment]
> > Consider sorting the two arrays
> 
> You mean in the alphabetic order Yeah i will consider that but the pull request is closed so 👌

ISo I don't think I will do anything

**Comment by NanduWasTaken** [comment]
Deleting the branch

**Comment by nikolaischunk** [comment]
@SkyDiscovery you cant just take content from one pr and put it in your own... its Nandus PR and his Domains that he found. let him add his Domains next time.

**Comment by NanduWasTaken** [comment]
> @SkyDiscovery you cant just take content from one pr and put it in your own... its Nandus PR and his Domains that he found. let him add his Domains next time.

Yoo whattt I don't even get contribution what the heck and he stole my domain yoooooo that's not cool!!

**Comment by SkyDiscovery** [comment]
> > @SkyDiscovery you cant just take content from one pr and put it in your own... its Nandus PR and his Domains that he found. let him add his Domains next time.
> 
> Yoo whattt I don't even get contribution what the heck and he stole my domain yoooooo that's not cool!!

I apologize again for the incident with this pull request. It was not my intention to steal any commits or contributions.

With kind regards Jonas

**Pull request closed without merging**
